# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos9610.dtb
dtbo-y += exynos9610-a50_swa_open_00.dtbo
dtbo-y += exynos9610-a50_swa_open_01.dtbo
dtbo-y += exynos9610-a50_swa_open_02.dtbo
dtbo-y += exynos9610-a50_swa_open_03.dtbo
dtbo-y += exynos9610-a50_swa_open_04.dtbo
dtbo-y += exynos9610-a50_swa_open_06.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
